#include <Arduino.h>
#include <Wire.h>
#include <Adafruit_GFX.h>
#include <Adafruit_SSD1306.h>
#include <Adafruit_NeoPixel.h>

//GENERATED BY AI ENTIRELY TO BE CHECKED AND TESTED 

// ---------- OLED Display ----------
#define SCREEN_WIDTH 128
#define SCREEN_HEIGHT 64
#define OLED_ADDR    0x3C   // typical I2C address, change if needed
Adafruit_SSD1306 display(SCREEN_WIDTH, SCREEN_HEIGHT, &Wire, -1);

// ---------- NeoPixel RGB ----------
#define NEOPIXEL_PIN    12
#define NUM_LEDS        1     // change if you have more
Adafruit_NeoPixel strip(NUM_LEDS, NEOPIXEL_PIN, NEO_GRB + NEO_KHZ800);

// ---------- Ultrasonic ----------
#define TRIG_PIN  9
#define ECHO_PIN  10

// ---------- Buzzer ----------
#define BUZZER_PIN 11

// ---------- Motor Driver (same as original) ----------
int PWMA = 6;
int AIN1 = A1;
int AIN2 = A0;
int PWMB = 5;
int BIN1 = A2;
int BIN2 = A3;

// ---------- Speed settings ----------
const int SPEED_NORMAL = 150;    // for free movement (>35 cm)
const int SPEED_CAUTIOUS = 100;  // for cautious (20‑35 cm)
const int SPEED_STOP = 0;        // for obstacle ≤20 cm

// ---------- Distance thresholds (cm) ----------
const int DIST_CRITICAL = 20;    // ≤20 → stop & turn
const int DIST_CAUTION = 35;     // 20‑35 → cautious forward

// ---------- Turn duration (ms) ----------
const unsigned long TURN_DURATION = 800;

// ---------- Global variables ----------
int distance = 0;                // current measured distance
bool isTurning = false;          // flag to avoid repeated turns
unsigned long turnStartTime = 0;

// ------------------------------------------------------------------
void setup() {
  // --- Motor pins ---
  pinMode(PWMA, OUTPUT);
  pinMode(AIN1, OUTPUT);
  pinMode(AIN2, OUTPUT);
  pinMode(PWMB, OUTPUT);
  pinMode(BIN1, OUTPUT);
  pinMode(BIN2, OUTPUT);

  // --- Ultrasonic pins ---
  pinMode(TRIG_PIN, OUTPUT);
  pinMode(ECHO_PIN, INPUT);

  // --- Buzzer ---
  pinMode(BUZZER_PIN, OUTPUT);
  digitalWrite(BUZZER_PIN, LOW);

  // --- NeoPixel ---
  strip.begin();
  strip.show(); // all off
  strip.setBrightness(50); // moderate brightness

  // --- OLED ---
  if (!display.begin(SSD1306_SWITCHCAPVCC, OLED_ADDR)) {
    // if OLED fails, loop forever (or you can ignore)
    for(;;);
  }
  display.clearDisplay();
  display.setTextColor(SSD1306_WHITE);
  display.setTextSize(1);
  display.setCursor(0,0);
  display.println("Alphabot Ready");
  display.display();
  delay(1000);

  // --- Serial (optional) ---
  Serial.begin(9600);
  Serial.println("Alphabot Obstacle Avoidance Started");
}

// ------------------------------------------------------------------
void loop() {
  // 1. Measure distance
  distance = getDistance();

  // 2. Decide action based on distance (unless we are in a turn)
  if (isTurning) {
    // We are currently turning right; check if turn time is over
    if (millis() - turnStartTime >= TURN_DURATION) {
      isTurning = false;
      stopMotors();
      Serial.println("Turn finished, resuming normal operation");
    }
    // else continue turning (motors are already set in the turn function)
  } else {
    // Normal operation: decide based on distance
    if (distance <= DIST_CRITICAL) {
      // Obstacle too close -> stop, turn right, beep, red LED
      handleObstacle();
    } else if (distance > DIST_CRITICAL && distance <= DIST_CAUTION) {
      // Cautious forward: yellow LED
      moveCautious();
    } else {
      // Free forward: green LED
      moveFree();
    }
  }

  // 3. Update OLED display with current distance and status
  updateOLED();

  // 4. Small delay to avoid excessive sensor readings
  delay(50);
}

// ------------------------------------------------------------------
// Ultrasonic distance measurement (cm)
// ------------------------------------------------------------------
int getDistance() {
  digitalWrite(TRIG_PIN, LOW);
  delayMicroseconds(2);
  digitalWrite(TRIG_PIN, HIGH);
  delayMicroseconds(10);
  digitalWrite(TRIG_PIN, LOW);
  long duration = pulseIn(ECHO_PIN, HIGH);
  int cm = duration * 0.034 / 2; // speed of sound = 343 m/s
  return cm;
}

// ------------------------------------------------------------------
// Motor control functions
// ------------------------------------------------------------------
void forward(int speed) {
  digitalWrite(AIN1, LOW);
  digitalWrite(AIN2, HIGH);
  digitalWrite(BIN1, LOW);
  digitalWrite(BIN2, HIGH);
  analogWrite(PWMA, speed);
  analogWrite(PWMB, speed);
}

void backward(int speed) {
  digitalWrite(AIN1, HIGH);
  digitalWrite(AIN2, LOW);
  digitalWrite(BIN1, HIGH);
  digitalWrite(BIN2, LOW);
  analogWrite(PWMA, speed);
  analogWrite(PWMB, speed);
}

void turnLeft(int speed) {
  // pivot left: left motor backward, right motor forward
  digitalWrite(AIN1, HIGH);
  digitalWrite(AIN2, LOW);
  digitalWrite(BIN1, LOW);
  digitalWrite(BIN2, HIGH);
  analogWrite(PWMA, speed);
  analogWrite(PWMB, speed);
}

void turnRight(int speed) {
  // pivot right: left motor forward, right motor backward
  digitalWrite(AIN1, LOW);
  digitalWrite(AIN2, HIGH);
  digitalWrite(BIN1, HIGH);
  digitalWrite(BIN2, LOW);
  analogWrite(PWMA, speed);
  analogWrite(PWMB, speed);
}

void stopMotors() {
  analogWrite(PWMA, 0);
  analogWrite(PWMB, 0);
}

// ------------------------------------------------------------------
// Action functions
// ------------------------------------------------------------------
void handleObstacle() {
  // Stop, beep, red LED, turn right for a fixed time
  stopMotors();
  setRGB(255, 0, 0);        // red
  beep(200);                // short beep
  delay(200);
  beep(200);
  delay(200);
  beep(200);

  // Turn right at normal speed
  turnRight(SPEED_NORMAL);
  Serial.println("Obstacle! Turning right...");
  isTurning = true;
  turnStartTime = millis();
}

void moveCautious() {
  forward(SPEED_CAUTIOUS);
  setRGB(255, 255, 0);      // yellow
  digitalWrite(BUZZER_PIN, LOW); // no beep
  Serial.println("Cautious forward");
}

void moveFree() {
  forward(SPEED_NORMAL);
  setRGB(0, 255, 0);        // green
  digitalWrite(BUZZER_PIN, LOW);
  Serial.println("Free forward");
}

// ------------------------------------------------------------------
// RGB LED control (NeoPixel)
// ------------------------------------------------------------------
void setRGB(byte r, byte g, byte b) {
  for (int i = 0; i < NUM_LEDS; i++) {
    strip.setPixelColor(i, r, g, b);
  }
  strip.show();
}

// ------------------------------------------------------------------
// Buzzer beep
// ------------------------------------------------------------------
void beep(int duration_ms) {
  digitalWrite(BUZZER_PIN, HIGH);
  delay(duration_ms);
  digitalWrite(BUZZER_PIN, LOW);
}

// ------------------------------------------------------------------
// OLED display update
// ------------------------------------------------------------------
void updateOLED() {
  display.clearDisplay();
  display.setTextSize(1);
  display.setTextColor(SSD1306_WHITE);
  display.setCursor(0, 0);
  display.print("Distance: ");
  display.print(distance);
  display.println(" cm");

  // Status line
  display.setCursor(0, 20);
  if (distance <= DIST_CRITICAL) {
    display.println("Status: OBSTACLE!");
  } else if (distance <= DIST_CAUTION) {
    display.println("Status: Cautious");
  } else {
    display.println("Status: Free");
  }

  // Show speed or extra info
  display.setCursor(0, 40);
  display.print("Speed: ");
  if (distance <= DIST_CRITICAL) {
    display.print("0 (stopped)");
  } else if (distance <= DIST_CAUTION) {
    display.print(SPEED_CAUTIOUS);
  } else {
    display.print(SPEED_NORMAL);
  }

  display.display();
}